server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/upulieh/spring-cloud-config-store
          search-paths:
          - '*service'